#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jul 24 10:23:29 2021

@author: yao
"""
num=int (input('enter a number-->'))
for i in range (0,num):
    i=i+1
    print("*"*i)
while (i!=0):
    i=i-1
    print('*'*i)
